version: "3.8"

services:
  drivernos:
    image: resb53/drivernos:latest
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "12"
    secrets:
      - drivernos-secret
    volumes:
      - .:/run/app/data:rw

secrets:
  drivernos-secret:
    external: true
