version: "3.8"

services:
  drivernos:
    image: resb53/drivernos:latest
    restart: always
    secrets:
      - drivernos-secret
    volumes:
      - drivernos:/run/app/data:rw

secrets:
  drivernos-secret:
    external: true
